// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDq0t1dDY1qYFFoIyp6nqShs2Rv4H9oA',
    appId: '1:246582440309:web:9a60774fa5b9331615a33c',
    messagingSenderId: '246582440309',
    projectId: 'gym-app-57eae',
    authDomain: 'gym-app-57eae.firebaseapp.com',
    storageBucket: 'gym-app-57eae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmEOlmw67RHdMOi83mXtsDEFveSybdA4',
    appId: '1:246582440309:android:d7e8a2f70d67c5c915a33c',
    messagingSenderId: '246582440309',
    projectId: 'gym-app-57eae',
    storageBucket: 'gym-app-57eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHl_i-NqGTCRlgmzxjXbGo6pIAXkwOQDs',
    appId: '1:246582440309:ios:2c00efb75824e0c615a33c',
    messagingSenderId: '246582440309',
    projectId: 'gym-app-57eae',
    storageBucket: 'gym-app-57eae.firebasestorage.app',
    iosBundleId: 'com.example.myGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHl_i-NqGTCRlgmzxjXbGo6pIAXkwOQDs',
    appId: '1:246582440309:ios:2c00efb75824e0c615a33c',
    messagingSenderId: '246582440309',
    projectId: 'gym-app-57eae',
    storageBucket: 'gym-app-57eae.firebasestorage.app',
    iosBundleId: 'com.example.myGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDq0t1dDY1qYFFoIyp6nqShs2Rv4H9oA',
    appId: '1:246582440309:web:2c098f30abe5a3ad15a33c',
    messagingSenderId: '246582440309',
    projectId: 'gym-app-57eae',
    authDomain: 'gym-app-57eae.firebaseapp.com',
    storageBucket: 'gym-app-57eae.firebasestorage.app',
  );
}
