name: Sync GitHub Labels

on:
  push:
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          yaml-file: .github/labels.yml
